// In-memory policy storage (in production, use a database)
export const samplePolicies = [
  {
    id: "1",
    policyId: "allow-read-docs",
    version: "1.0.0",
    effect: "PERMIT" as const,
    description: "Allow users to read documents",
    conditions: {
      type: "equals" as const,
      left: "subject.role",
      right: "user",
    },
    isActive: true,
    category: "document",
    tags: ["read"],
    createdBy: "admin",
    createdAt: new Date().toISOString(),
    updatedBy: null,
    updatedAt: new Date().toISOString(),
    deletedAt: null,
    deletedBy: null,
  },
  {
    id: "2",
    policyId: "allow-admin-all",
    version: "1.0.0",
    effect: "PERMIT" as const,
    description: "Allow admins to do everything",
    conditions: {
      type: "equals" as const,
      left: "subject.role",
      right: "admin",
    },
    isActive: true,
    category: "admin",
    tags: ["admin", "all"],
    createdBy: "admin",
    createdAt: new Date().toISOString(),
    updatedBy: null,
    updatedAt: new Date().toISOString(),
    deletedAt: null,
    deletedBy: null,
  },
  {
    id: "3",
    policyId: "deny-delete-critical",
    version: "1.0.0",
    effect: "DENY" as const,
    description: "Deny deletion of critical resources",
    conditions: {
      type: "and" as const,
      conditions: [
        { type: "equals" as const, left: "action", right: "delete" },
        { type: "equals" as const, left: "resource.critical", right: true },
      ],
    },
    isActive: true,
    category: "security",
    tags: ["delete", "critical"],
    createdBy: "admin",
    createdAt: new Date().toISOString(),
    updatedBy: null,
    updatedAt: new Date().toISOString(),
    deletedAt: null,
    deletedBy: null,
  },
];

export let policies = [...samplePolicies];
